# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conversation.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63onversation.proto\x12\x0c\x63onversation\"\x1a\n\x18StartConversationRequest\"*\n\x19StartConversationResponse\x12\r\n\x05timer\x18\x01 \x01(\t\"?\n\x04Word\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\r\n\x05start\x18\x03 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x04 \x01(\x01\"\x99\x01\n\x08Sentence\x12\x13\n\x0bsentence_id\x18\x01 \x01(\t\x12\x12\n\nspeaker_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x17\n\x0fsentiment_score\x18\x04 \x01(\x02\x12!\n\x05words\x18\x05 \x03(\x0b\x32\x12.conversation.Word\x12\r\n\x05start\x18\x06 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x07 \x01(\x01\":\n\x05Topic\x12\x10\n\x08topic_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\trelevance\x18\x03 \x01(\x02\"\xc8\x01\n\x04Turn\x12\x0f\n\x07turn_id\x18\x01 \x01(\t\x12\x12\n\nspeaker_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12)\n\tsentences\x18\x04 \x03(\x0b\x32\x16.conversation.Sentence\x12!\n\x05words\x18\x05 \x03(\x0b\x32\x12.conversation.Word\x12#\n\x06topics\x18\x06 \x03(\x0b\x32\x13.conversation.Topic\x12\r\n\x05start\x18\x07 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x08 \x01(\x01\"8\n\x0eGetTurnRequest\x12\x0f\n\x07turn_id\x18\x01 \x01(\t\x12\x15\n\rinclude_words\x18\x02 \x01(\x08\"/\n\x16GetConversationRequest\x12\x15\n\rinclude_words\x18\x01 \x01(\x08\"V\n\x0c\x43onversation\x12!\n\x05turns\x18\x01 \x03(\x0b\x32\x12.conversation.Turn\x12#\n\x06topics\x18\x02 \x03(\x0b\x32\x13.conversation.Topic2\x8f\x02\n\x13\x43onversationService\x12;\n\x07GetTurn\x12\x1c.conversation.GetTurnRequest\x1a\x12.conversation.Turn\x12S\n\x0fGetConversation\x12$.conversation.GetConversationRequest\x1a\x1a.conversation.Conversation\x12\x66\n\x11StartConversation\x12&.conversation.StartConversationRequest\x1a\'.conversation.StartConversationResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTCONVERSATIONREQUEST']._serialized_start=36
  _globals['_STARTCONVERSATIONREQUEST']._serialized_end=62
  _globals['_STARTCONVERSATIONRESPONSE']._serialized_start=64
  _globals['_STARTCONVERSATIONRESPONSE']._serialized_end=106
  _globals['_WORD']._serialized_start=108
  _globals['_WORD']._serialized_end=171
  _globals['_SENTENCE']._serialized_start=174
  _globals['_SENTENCE']._serialized_end=327
  _globals['_TOPIC']._serialized_start=329
  _globals['_TOPIC']._serialized_end=387
  _globals['_TURN']._serialized_start=390
  _globals['_TURN']._serialized_end=590
  _globals['_GETTURNREQUEST']._serialized_start=592
  _globals['_GETTURNREQUEST']._serialized_end=648
  _globals['_GETCONVERSATIONREQUEST']._serialized_start=650
  _globals['_GETCONVERSATIONREQUEST']._serialized_end=697
  _globals['_CONVERSATION']._serialized_start=699
  _globals['_CONVERSATION']._serialized_end=785
  _globals['_CONVERSATIONSERVICE']._serialized_start=788
  _globals['_CONVERSATIONSERVICE']._serialized_end=1059
# @@protoc_insertion_point(module_scope)
