# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_loaders.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_loaders.proto\x12\x0b\x44\x61taLoaders\"\'\n\x13ProcessVideoRequest\x12\x10\n\x08\x66ile_url\x18\x01 \x01(\t\"V\n\x14ProcessVideoResponse\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x13\n\x0bvideo_title\x18\x02 \x01(\t\x12\x17\n\x0fprocessing_time\x18\x03 \x01(\t\"3\n\x1bProcessVideoPlaylistRequest\x12\x14\n\x0cplaylist_url\x18\x01 \x01(\t\"\xae\x01\n\x1cProcessVideoPlaylistResponse\x12\x1f\n\x17last_processed_video_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_videos\x18\x02 \x01(\x05\x12\x1e\n\x16processed_videos_count\x18\x03 \x01(\x05\x12\x16\n\x0etotal_duration\x18\x04 \x01(\t\x12\x1f\n\x17\x65xpected_time_to_finish\x18\x05 \x01(\t2\xd6\x01\n\x10YouTubeProcessor\x12S\n\x0cProcessVideo\x12 .DataLoaders.ProcessVideoRequest\x1a!.DataLoaders.ProcessVideoResponse\x12m\n\x14ProcessVideoPlaylist\x12(.DataLoaders.ProcessVideoPlaylistRequest\x1a).DataLoaders.ProcessVideoPlaylistResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_loaders_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROCESSVIDEOREQUEST']._serialized_start=35
  _globals['_PROCESSVIDEOREQUEST']._serialized_end=74
  _globals['_PROCESSVIDEORESPONSE']._serialized_start=76
  _globals['_PROCESSVIDEORESPONSE']._serialized_end=162
  _globals['_PROCESSVIDEOPLAYLISTREQUEST']._serialized_start=164
  _globals['_PROCESSVIDEOPLAYLISTREQUEST']._serialized_end=215
  _globals['_PROCESSVIDEOPLAYLISTRESPONSE']._serialized_start=218
  _globals['_PROCESSVIDEOPLAYLISTRESPONSE']._serialized_end=392
  _globals['_YOUTUBEPROCESSOR']._serialized_start=395
  _globals['_YOUTUBEPROCESSOR']._serialized_end=609
# @@protoc_insertion_point(module_scope)
