# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: composition.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63omposition.proto\x12\x0b\x63omposition\"A\n\x15GetCompositionRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x16\n\x0e\x63omposition_id\x18\x02 \x01(\t\"G\n\x16GetCompositionResponse\x12-\n\x0b\x63omposition\x18\x01 \x01(\x0b\x32\x18.composition.Composition\"g\n\x0b\x43omposition\x12+\n\x05items\x18\x01 \x03(\x0b\x32\x1c.composition.CompositionItem\x12+\n\x08metadata\x18\x64 \x01(\x0b\x32\x19.composition.FileMetadata\"\x95\x01\n\x0f\x43ompositionItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bsource_path\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x10\n\x08\x64uration\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12+\n\x08metadata\x18\x64 \x01(\x0b\x32\x19.composition.FileMetadata\"p\n\nYTMetadata\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x12\n\nchannel_id\x18\x02 \x01(\t\x12\x13\n\x0bupload_date\x18\x03 \x01(\t\x12\x12\n\nview_count\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"C\n\x0c\x46ileMetadata\x12\x12\n\ncreated_at\x18\x01 \x01(\t\x12\x10\n\x08\x66ilepath\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t2o\n\x12\x43ompositionService\x12Y\n\x0eGetComposition\x12\".composition.GetCompositionRequest\x1a#.composition.GetCompositionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'composition_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETCOMPOSITIONREQUEST']._serialized_start=34
  _globals['_GETCOMPOSITIONREQUEST']._serialized_end=99
  _globals['_GETCOMPOSITIONRESPONSE']._serialized_start=101
  _globals['_GETCOMPOSITIONRESPONSE']._serialized_end=172
  _globals['_COMPOSITION']._serialized_start=174
  _globals['_COMPOSITION']._serialized_end=277
  _globals['_COMPOSITIONITEM']._serialized_start=280
  _globals['_COMPOSITIONITEM']._serialized_end=429
  _globals['_YTMETADATA']._serialized_start=431
  _globals['_YTMETADATA']._serialized_end=543
  _globals['_FILEMETADATA']._serialized_start=545
  _globals['_FILEMETADATA']._serialized_end=612
  _globals['_COMPOSITIONSERVICE']._serialized_start=614
  _globals['_COMPOSITIONSERVICE']._serialized_end=725
# @@protoc_insertion_point(module_scope)
